/*
 * Message API (MAPI) definitions for libexe
 *
 * Copyright (c) 2011, Joachim Metz <jbmetz@users.sourceforge.net>
 *
 * Refer to AUTHORS for acknowledgements.
 *
 * This software is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this software.  If not, see <http://www.gnu.org/licenses/>.
 */

#if !defined( _LIBEXE_MAPI_H )
#define _LIBEXE_MAPI_H

#include <libexe/types.h>

#ifdef __cplusplus
extern "C" {
#endif

/* The attachment methods
 */
enum LIBEXE_ATTACHMENT_METHODS
{
	LIBEXE_ATTACHMENT_METHOD_NONE						= 0,
	LIBEXE_ATTACHMENT_METHOD_BY_VALUE					= 1,
	LIBEXE_ATTACHMENT_METHOD_BY_REFERENCE					= 2,
	LIBEXE_ATTACHMENT_METHOD_BY_REFERENCE_RESOLVE				= 3,
	LIBEXE_ATTACHMENT_METHOD_BY_REFERENCE_ONLY				= 4,
	LIBEXE_ATTACHMENT_METHOD_EMBEDDED_MESSAGE				= 5,
	LIBEXE_ATTACHMENT_METHOD_OLE						= 6
};

/* The message flags
 */
enum LIBEXE_MESSAGE_FLAGS
{
	LIBEXE_MESSAGE_FLAG_READ						= 0x00000001,
	LIBEXE_MESSAGE_FLAG_UNMODIFIED						= 0x00000002,
	LIBEXE_MESSAGE_FLAG_SUBMIT						= 0x00000004,
	LIBEXE_MESSAGE_FLAG_UNSENT						= 0x00000008,
	LIBEXE_MESSAGE_FLAG_HAS_ATTACHMENTS					= 0x00000010,
	LIBEXE_MESSAGE_FLAG_FROM_ME						= 0x00000020,
	LIBEXE_MESSAGE_FLAG_ASSOCIATED						= 0x00000040,
	LIBEXE_MESSAGE_FLAG_RESEND						= 0x00000080,
	LIBEXE_MESSAGE_FLAG_RN_PENDING						= 0x00000100,
	LIBEXE_MESSAGE_FLAG_NRN_PENDING						= 0x00000200
};

/* The message importance types
 */
enum LIBEXE_MESSAGE_IMPORTANCE_TYPES
{
	LIBEXE_MESSAGE_IMPORTANCE_TYPE_LOW					= 0,
	LIBEXE_MESSAGE_IMPORTANCE_TYPE_NORMAL					= 1,
	LIBEXE_MESSAGE_IMPORTANCE_TYPE_HIGH					= 2
};

/* The message priority types
 */
enum LIBEXE_MESSAGE_PRIORITY_TYPES
{
	LIBEXE_MESSAGE_PRIORITY_TYPE_NON_URGENT					= -1,
	LIBEXE_MESSAGE_PRIORITY_TYPE_NORMAL					= 0,
	LIBEXE_MESSAGE_PRIORITY_TYPE_URGENT					= 1
};

/* The message sensitivity types
 */
enum LIBEXE_MESSAGE_SENSITIVITY_TYPES
{
	LIBEXE_MESSAGE_SENSITIVITY_TYPE_NONE					= 0,
	LIBEXE_MESSAGE_SENSITIVITY_TYPE_PERSONAL				= 1,
	LIBEXE_MESSAGE_SENSITIVITY_TYPE_PRIVATE					= 2,
	LIBEXE_MESSAGE_SENSITIVITY_TYPE_CONFIDENTIAL				= 3
};

/* The message store valid folder masks
 */
enum LIBEXE_MESSAGE_STORE_VALID_FOLDER_MASKS
{
	LIBEXE_VALID_FOLDER_MASK_SUBTREE					= 0x00000001,
	LIBEXE_VALID_FOLDER_MASK_INBOX						= 0x00000002,
	LIBEXE_VALID_FOLDER_MASK_OUTBOX						= 0x00000004,
	LIBEXE_VALID_FOLDER_MASK_WASTEBOX					= 0x00000008,
	LIBEXE_VALID_FOLDER_MASK_SENTMAIL					= 0x00000010,
	LIBEXE_VALID_FOLDER_MASK_VIEWS						= 0x00000020,
	LIBEXE_VALID_FOLDER_MASK_COMMON_VIEWS					= 0x00000040,
	LIBEXE_VALID_FOLDER_MASK_FINDER						= 0x00000080
};

/* The object types
 * TODO
enum LIBEXE_OBJECT_TYPES
{
	MAPI_STORE	= 0x00000001,
	MAPI_ADDRBOOK	= 0x00000002,
	MAPI_FOLDER	= 0x00000003,
	MAPI_ABCONT	= 0x00000004,
	MAPI_MESSAGE	= 0x00000005,
	MAPI_MAILUSER	= 0x00000006,
	MAPI_ATTACH	= 0x00000007,
	MAPI_DISTLIST	= 0x00000008,
	MAPI_PROFSECT	= 0x00000009,
	MAPI_STATUS	= 0x0000000a,
	MAPI_SESSION	= 0x0000000b,
	MAPI_FORMINFO	= 0x0000000c
};
 */

/* The recipient type
 */
enum LIBEXE_RECIPIENT_TYPES
{
	LIBEXE_RECIPIENT_TYPE_ORIGINATOR					= 0,
	LIBEXE_RECIPIENT_TYPE_TO						= 1,
	LIBEXE_RECIPIENT_TYPE_CC						= 2,
	LIBEXE_RECIPIENT_TYPE_BCC						= 3
};

/* The value types
 */
enum LIBEXE_VALUE_TYPES
{
	LIBEXE_VALUE_TYPE_UNSPECIFIED						= 0x0000,
	LIBEXE_VALUE_TYPE_NULL							= 0x0001,
	LIBEXE_VALUE_TYPE_INTEGER_16BIT_SIGNED					= 0x0002,
	LIBEXE_VALUE_TYPE_INTEGER_32BIT_SIGNED					= 0x0003,
	LIBEXE_VALUE_TYPE_FLOAT_32BIT						= 0x0004,
	LIBEXE_VALUE_TYPE_DOUBLE_64BIT						= 0x0005,
	LIBEXE_VALUE_TYPE_CURRENCY						= 0x0006,
	LIBEXE_VALUE_TYPE_APPLICATION_TIME					= 0x0007,
	LIBEXE_VALUE_TYPE_ERROR							= 0x000a,
	LIBEXE_VALUE_TYPE_BOOLEAN						= 0x000b,
	LIBEXE_VALUE_TYPE_OBJECT						= 0x000d,
	LIBEXE_VALUE_TYPE_INTEGER_64BIT_SIGNED					= 0x0014,
	LIBEXE_VALUE_TYPE_STRING_ASCII						= 0x001e,
	LIBEXE_VALUE_TYPE_STRING_UNICODE					= 0x001f,
	LIBEXE_VALUE_TYPE_FILETIME						= 0x0040,
	LIBEXE_VALUE_TYPE_GUID							= 0x0048,
	LIBEXE_VALUE_TYPE_SERVER_IDENTIFIER					= 0x00fb,
	LIBEXE_VALUE_TYPE_RESTRICTION						= 0x00fd,
	LIBEXE_VALUE_TYPE_RULE_ACTION						= 0x00fe,
	LIBEXE_VALUE_TYPE_BINARY_DATA						= 0x0102,
	LIBEXE_VALUE_TYPE_MULTI_VALUE_INTEGER_16BIT_SIGNED			= 0x1002,
	LIBEXE_VALUE_TYPE_MULTI_VALUE_INTEGER_32BIT_SIGNED			= 0x1003,
	LIBEXE_VALUE_TYPE_MULTI_VALUE_FLOAT_32BIT				= 0x1004,
	LIBEXE_VALUE_TYPE_MULTI_VALUE_DOUBLE_64BIT				= 0x1005,
	LIBEXE_VALUE_TYPE_MULTI_VALUE_CURRENCY					= 0x1006,
	LIBEXE_VALUE_TYPE_MULTI_VALUE_APPLICATION_TIME				= 0x1007,
	LIBEXE_VALUE_TYPE_MULTI_VALUE_INTEGER_64BIT_SIGNED			= 0x1014,
	LIBEXE_VALUE_TYPE_MULTI_VALUE_STRING_ASCII				= 0x101e,
	LIBEXE_VALUE_TYPE_MULTI_VALUE_STRING_UNICODE				= 0x101f,
	LIBEXE_VALUE_TYPE_MULTI_VALUE_FILETIME					= 0x1040,
	LIBEXE_VALUE_TYPE_MULTI_VALUE_GUID					= 0x1048,
	LIBEXE_VALUE_TYPE_MULTI_VALUE_BINARY_DATA				= 0x1102
};

#define LIBEXE_VALUE_TYPE_MULTI_VALUE_FLAG					0x1000

/* The entry types
 */
enum LIBEXE_ENTRY_TYPES
{
	LIBEXE_ENTRY_TYPE_MESSAGE_IMPORTANCE					= 0x0017,

	LIBEXE_ENTRY_TYPE_MESSAGE_CLASS						= 0x001a,

	LIBEXE_ENTRY_TYPE_MESSAGE_PRIORITY					= 0x0026,

	LIBEXE_ENTRY_TYPE_MESSAGE_SENSITIVITY					= 0x0036,
	LIBEXE_ENTRY_TYPE_MESSAGE_SUBJECT					= 0x0037,

	LIBEXE_ENTRY_TYPE_MESSAGE_CLIENT_SUBMIT_TIME				= 0x0039,

	LIBEXE_ENTRY_TYPE_MESSAGE_SENT_REPRESENTING_SEARCH_KEY			= 0x003b,

	LIBEXE_ENTRY_TYPE_MESSAGE_RECEIVED_BY_ENTRY_IDENTIFIER			= 0x003f,
	LIBEXE_ENTRY_TYPE_MESSAGE_RECEIVED_BY_NAME				= 0x0040,
	LIBEXE_ENTRY_TYPE_MESSAGE_SENT_REPRESENTING_ENTRY_IDENTIFIER		= 0x0041,
	LIBEXE_ENTRY_TYPE_MESSAGE_SENT_REPRESENTING_NAME			= 0x0042,
	LIBEXE_ENTRY_TYPE_MESSAGE_RECEIVED_REPRESENTING_ENTRY_IDENTIFIER	= 0x0043,
	LIBEXE_ENTRY_TYPE_MESSAGE_RECEIVED_REPRESENTING_NAME			= 0x0044,

	LIBEXE_ENTRY_TYPE_MESSAGE_REPLY_RECIPIENT_ENTRIES			= 0x004f,
	LIBEXE_ENTRY_TYPE_MESSAGE_REPLY_RECIPIENT_NAMES				= 0x0050,
	LIBEXE_ENTRY_TYPE_MESSAGE_RECEIVED_BY_SEARCH_KEY			= 0x0051,
	LIBEXE_ENTRY_TYPE_MESSAGE_RECEIVED_REPRESENTING_SEARCH_KEY		= 0x0052,

	LIBEXE_ENTRY_TYPE_MESSAGE_SENT_REPRESENTING_ADDRESS_TYPE		= 0x0064,
	LIBEXE_ENTRY_TYPE_MESSAGE_SENT_REPRESENTING_EMAIL_ADDRESS		= 0x0065,

	LIBEXE_ENTRY_TYPE_MESSAGE_CONVERSATION_TOPIC				= 0x0070,
	LIBEXE_ENTRY_TYPE_MESSAGE_CONVERSATION_INDEX				= 0x0071,

	LIBEXE_ENTRY_TYPE_MESSAGE_RECEIVED_BY_ADDRESS_TYPE			= 0x0075,
	LIBEXE_ENTRY_TYPE_MESSAGE_RECEIVED_BY_EMAIL_ADDRESS			= 0x0076,
	LIBEXE_ENTRY_TYPE_MESSAGE_RECEIVED_REPRESENTING_ADDRESS_TYPE		= 0x0077,
	LIBEXE_ENTRY_TYPE_MESSAGE_RECEIVED_REPRESENTING_EMAIL_ADDRESS		= 0x0078,

	LIBEXE_ENTRY_TYPE_MESSAGE_TRANSPORT_HEADERS				= 0x007d,

	LIBEXE_ENTRY_TYPE_RECIPIENT_TYPE					= 0x0c15,

	LIBEXE_ENTRY_TYPE_MESSAGE_SENDER_ENTRY_IDENTIFIER			= 0x0c19,
	LIBEXE_ENTRY_TYPE_MESSAGE_SENDER_NAME					= 0x0c1a,

	LIBEXE_ENTRY_TYPE_MESSAGE_SENDER_SEARCH_KEY				= 0x0c1d,
	LIBEXE_ENTRY_TYPE_MESSAGE_SENDER_ADDRESS_TYPE				= 0x0c1e,
	LIBEXE_ENTRY_TYPE_MESSAGE_SENDER_EMAIL_ADDRESS				= 0x0c1f,

	LIBEXE_ENTRY_TYPE_MESSAGE_DISPLAY_TO					= 0x0e04,

	LIBEXE_ENTRY_TYPE_MESSAGE_DELIVERY_TIME					= 0x0e06,
	LIBEXE_ENTRY_TYPE_MESSAGE_FLAGS						= 0x0e07,
	LIBEXE_ENTRY_TYPE_MESSAGE_SIZE						= 0x0e08,

	LIBEXE_ENTRY_TYPE_MESSAGE_STATUS					= 0x0e17,

	LIBEXE_ENTRY_TYPE_ATTACHMENT_SIZE					= 0x0e20,

	LIBEXE_ENTRY_TYPE_MESSAGE_INTERNET_ARTICLE_NUMBER			= 0x0e23,

	LIBEXE_ENTRY_TYPE_MESSAGE_PERMISSION					= 0x0e27,

	LIBEXE_ENTRY_TYPE_MESSAGE_URL_COMPUTER_NAME_SET				= 0x0e62,

	LIBEXE_ENTRY_TYPE_MESSAGE_TRUST_SENDER					= 0x0e79,

	LIBEXE_ENTRY_TYPE_MESSAGE_BODY_PLAIN_TEXT				= 0x1000,

	LIBEXE_ENTRY_TYPE_MESSAGE_BODY_COMPRESSED_RTF				= 0x1009,

	LIBEXE_ENTRY_TYPE_MESSAGE_BODY_HTML					= 0x1013,

	LIBEXE_ENTRY_TYPE_EMAIL_EML_FILENAME					= 0x10f3,

	LIBEXE_ENTRY_TYPE_DISPLAY_NAME						= 0x3001,
	LIBEXE_ENTRY_TYPE_ADDRESS_TYPE						= 0x3002,
	LIBEXE_ENTRY_TYPE_EMAIL_ADDRESS						= 0x3003,

	LIBEXE_ENTRY_TYPE_MESSAGE_CREATION_TIME					= 0x3007,
	LIBEXE_ENTRY_TYPE_MESSAGE_MODIFICATION_TIME				= 0x3008,

	LIBEXE_ENTRY_TYPE_MESSAGE_STORE_VALID_FOLDER_MASK			= 0x35df,

	LIBEXE_ENTRY_TYPE_FOLDER_TYPE						= 0x3601,
	LIBEXE_ENTRY_TYPE_NUMBER_OF_CONTENT_ITEMS				= 0x3602,
	LIBEXE_ENTRY_TYPE_NUMBER_OF_UNREAD_CONTENT_ITEMS			= 0x3603,

	LIBEXE_ENTRY_TYPE_HAS_SUB_FOLDERS					= 0x360a,

	LIBEXE_ENTRY_TYPE_CONTAINER_CLASS					= 0x3613,

	LIBEXE_ENTRY_TYPE_NUMBER_OF_ASSOCIATED_CONTENT				= 0x3617,

	LIBEXE_ENTRY_TYPE_ATTACHMENT_DATA_OBJECT				= 0x3701,

	LIBEXE_ENTRY_TYPE_ATTACHMENT_FILENAME_SHORT				= 0x3704,
	LIBEXE_ENTRY_TYPE_ATTACHMENT_METHOD					= 0x3705,

	LIBEXE_ENTRY_TYPE_ATTACHMENT_FILENAME_LONG				= 0x3707,

	LIBEXE_ENTRY_TYPE_ATTACHMENT_RENDERING_POSITION				= 0x370b,

	LIBEXE_ENTRY_TYPE_CONTACT_CALLBACK_PHONE_NUMBER				= 0x3a02,

	LIBEXE_ENTRY_TYPE_CONTACT_GENERATIONAL_ABBREVIATION			= 0x3a05,
	LIBEXE_ENTRY_TYPE_CONTACT_GIVEN_NAME					= 0x3a06,

	LIBEXE_ENTRY_TYPE_CONTACT_BUSINESS_PHONE_NUMBER_1			= 0x3a08,
	LIBEXE_ENTRY_TYPE_CONTACT_HOME_PHONE_NUMBER				= 0x3a09,
	LIBEXE_ENTRY_TYPE_CONTACT_INITIALS					= 0x3a0a,

	LIBEXE_ENTRY_TYPE_CONTACT_SURNAME					= 0x3a11,

	LIBEXE_ENTRY_TYPE_CONTACT_POSTAL_ADDRESS				= 0x3a15,
	LIBEXE_ENTRY_TYPE_CONTACT_COMPANY_NAME					= 0x3a16,
	LIBEXE_ENTRY_TYPE_CONTACT_JOB_TITLE					= 0x3a17,
	LIBEXE_ENTRY_TYPE_CONTACT_DEPARTMENT_NAME				= 0x3a18,
	LIBEXE_ENTRY_TYPE_CONTACT_OFFICE_LOCATION				= 0x3a19,
	LIBEXE_ENTRY_TYPE_CONTACT_PRIMARY_PHONE_NUMBER				= 0x3a1a,
	LIBEXE_ENTRY_TYPE_CONTACT_BUSINESS_PHONE_NUMBER_2			= 0x3a1b,
	LIBEXE_ENTRY_TYPE_CONTACT_MOBILE_PHONE_NUMBER				= 0x3a1c,

	LIBEXE_ENTRY_TYPE_CONTACT_BUSINESS_FAX_NUMBER				= 0x3a24,

	LIBEXE_ENTRY_TYPE_CONTACT_COUNTRY					= 0x3a26,
	LIBEXE_ENTRY_TYPE_CONTACT_LOCALITY					= 0x3a27,

	LIBEXE_ENTRY_TYPE_CONTACT_TITLE						= 0x3a45,

	LIBEXE_ENTRY_TYPE_MESSAGE_BODY_CODEPAGE					= 0x3fde,

	LIBEXE_ENTRY_TYPE_MESSAGE_CODEPAGE					= 0x3ffd,

	LIBEXE_ENTRY_TYPE_RECIPIENT_DISPLAY_NAME				= 0x5ff6,

	LIBEXE_ENTRY_TYPE_FOLDER_CHILD_COUNT					= 0x6638,

	LIBEXE_ENTRY_TYPE_SUB_ITEM_IDENTIFIER					= 0x67f2,

	LIBEXE_ENTRY_TYPE_MESSAGE_STORE_PASSWORD_CHECKSUM			= 0x67ff,

	LIBEXE_ENTRY_TYPE_ADDRESS_FILE_UNDER					= 0x8005,

	LIBEXE_ENTRY_TYPE_TASK_STATUS						= 0x8101,
	LIBEXE_ENTRY_TYPE_TASK_PERCENTAGE_COMPLETE				= 0x8102,

	LIBEXE_ENTRY_TYPE_TASK_START_DATE					= 0x8104,
	LIBEXE_ENTRY_TYPE_TASK_DUE_DATE						= 0x8105,

	LIBEXE_ENTRY_TYPE_TASK_ACTUAL_EFFORT					= 0x8110,
	LIBEXE_ENTRY_TYPE_TASK_TOTAL_EFFORT					= 0x8111,
	LIBEXE_ENTRY_TYPE_TASK_VERSION						= 0x8112,

	LIBEXE_ENTRY_TYPE_TASK_IS_COMPLETE					= 0x811c,

	LIBEXE_ENTRY_TYPE_TASK_IS_RECURRING					= 0x8126,

	LIBEXE_ENTRY_TYPE_APPOINTMENT_BUSY_STATUS				= 0x8205,

	LIBEXE_ENTRY_TYPE_APPOINTMENT_LOCATION					= 0x8208,

	LIBEXE_ENTRY_TYPE_APPOINTMENT_START_TIME				= 0x820d,
	LIBEXE_ENTRY_TYPE_APPOINTMENT_END_TIME					= 0x820e,

	LIBEXE_ENTRY_TYPE_APPOINTMENT_DURATION					= 0x8213,

	LIBEXE_ENTRY_TYPE_APPOINTMENT_IS_RECURRING				= 0x8223,

	LIBEXE_ENTRY_TYPE_APPOINTMENT_RECURRENCE_PATTERN			= 0x8232,

	LIBEXE_ENTRY_TYPE_APPOINTMENT_TIMEZONE_DESCRIPTION			= 0x8234,
	LIBEXE_ENTRY_TYPE_APPOINTMENT_FIRST_EFFECTIVE_TIME			= 0x8235,
	LIBEXE_ENTRY_TYPE_APPOINTMENT_LAST_EFFECTIVE_TIME			= 0x8236,

	LIBEXE_ENTRY_TYPE_MESSAGE_REMINDER_TIME					= 0x8502,
	LIBEXE_ENTRY_TYPE_MESSAGE_IS_REMINDER					= 0x8503,

	LIBEXE_ENTRY_TYPE_MESSAGE_IS_PRIVATE					= 0x8506,

	LIBEXE_ENTRY_TYPE_MESSAGE_REMINDER_SIGNAL_TIME				= 0x8550
};

#define LIBEXE_ENTRY_TYPE_AMOUNT_OF_CONTENT_ITEMS		LIBEXE_ENTRY_TYPE_NUMBER_OF_CONTENT_ITEMS
#define LIBEXE_ENTRY_TYPE_AMOUNT_OF_UNREAD_CONTENT_ITEMS	LIBEXE_ENTRY_TYPE_NUMBER_OF_UNREAD_CONTENT_ITEMS
#define LIBEXE_ENTRY_TYPE_AMOUNT_OF_ASSOCIATED_CONTENT		LIBEXE_ENTRY_TYPE_NUMBER_OF_ASSOCIATED_CONTENT

#ifdef __cplusplus
}
#endif

#endif

